name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Install go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ env.GO_VERSION }}'
      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libvips-dev
          go mod download
      # Build all
      - name: Build
        run: make build
